files:
  train: "202502_data_train.csv"
  test: "202302_data_test.csv"
folders:
  data: "data/"
  models: "models/"
mlflow:
  experiment_name: "watergenic-202502-data"
  tracking_server: False # if True, make sure tracking server is running
  uri: "http://localhost:5000"
n_data_points: 5 # Number of data points to use for dynamic training (must be >= 4)
